baseURL = "https://tenbarge.dev/"
title = "Cory Tenbarge"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-154221637-1"

[params]
    #author = "Cory Tenbarge"
    #info = "params.info"
    description = "params.description"
    keywords = "blog,developer,personal"
    #avatarurl = "images/avatar.jpg"

    #favicon_32 = "/img/favicon-32x32.png"
    #favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "footercontent"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/tenbarge/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/corytenbarge/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/cory-tenbarge-b377a919/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 3
    url = "https://medium.com/@cory.tenbarge/"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 3
    url = "https://stackoverflow.com/users/9979840/tenbarge/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
